/*
Copyright IBM Corp. 2017 All Rights Reserved.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
		 http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

'use strict';

const  fs = require('fs');
const hfc = require('fabric-client');

exports.command = 'chaincode <command>';
exports.desc = 'Install, instantiate and update chaincode';
exports.builder = function (yargs) {
    return yargs.commandDir('chaincode-cmds')
    .option('net-config', {
        demandOption: true,
        describe: 'Absolute path for network config file based on  FAB-5363 format',
        type: 'string'
    }).check(function(argv){
        //validate file exists
        if (! fs.existsSync(argv['net-config'])){
            throw(new Error('Invalid --net-config argument.  File does not exist: ' + argv['net-config']));
        }
        //validate file format
        let netConfig = require(argv['net-config']);
        if(!netConfig.hasOwnProperty('network-config')){
            throw(new Error('Invalid --net-config argument.  Invalid format, missing network-config key.'));
        }
        return true;
    }).option('org', {
        demandOption: true,
        describe: 'Name of org stanza in the network-config file that contains the peers where the chaincode should be installed',
        requiresArg: true,
        type: 'string'
    }).check(function(argv){
        //get the network configuration file.  by now this has already been validated that it exists
        hfc.addConfigFile(argv['net-config']);
        //make sure the org specified is in the network-config file 
        let orgs = hfc.getConfigSetting('network-config');
        if(!orgs[argv.org]){
            throw(new Error('Invalid --org argument. Organization \'' + argv.org + '\' not found in network-config file.'));
        }
        return true;
    }).option('crypto-dir', {
        demandOption: true,
        describe: 'Absolute path for crypto material as generated by cryptogen tool',
        type: 'string'
    }).check(function(argv){
        if (! fs.existsSync(argv['crypto-dir'])){
            throw(new Error('Invalid --crypto-dir argument.  Directory does not exist: ' + argv['crypto-dir']));
        } 
        return true;
    });
};
exports.handler = function (argv) {

    console.log("####### calling handler ########");

};